### PR TITLE
Collaboration service

### PR DESCRIPTION
**Pull request by inezkok**
Milestone 5 Tasks:
- [x] Connect matching to collab room
- [x] Collaborative code editor
- [x] Ensure that only matched users can enter collab (through start session button)
- [x] Retrieve question based on matched preferences
- [x] Change retrieve question logic to randomly pick a question that matches preferences
- [x] Improve question display on Collab page to show Topic(s) and Difficulty
- [x] Implement disconnected mechanism - allow user to reconnect??
- [x] Implement user quit - when one user quit, notify other user
- [x] Collaboration timer
- [x] Implement timeout - users have to extend session after 30mins, if user doesn't extend for a period of time (eg 30s then treat as user AFK and quit the session)

### CODE REVIEW

**Comment by ChillinRage** [comment]
idk if is just me, but I got this error when I was in a collab session and I pressed f12 to open the console

image

**Comment by inezkok** [comment]
> idk if is just me, but I got this error when I was in a collab session and I pressed f12 to open the console
> 
> image

@ChillinRage hmmm how did you get this error (like how can i try to recreate it)? oso the console just shows a warning which shouldn't be related to the error you are getting...

**Comment by ChillinRage** [comment]
> > idk if is just me, but I got this error when I was in a collab session and I pressed f12 to open the console
> > image
> 
> @ChillinRage hmmm how did you get this error (like how can i try to recreate it)? oso the console just shows a warning which shouldn't be related to the error you are getting...

I just tried again. Seems like this error only happens for me when the browser is in full screen (i just pressed F12 to open and close the console while in a session). I can send a screen recording if you'd like.

**Comment by ChillinRage** [comment]
I might be losing my mind here, but just to check, are there any database for the collab service?

**Review by miljyy — APPROVED** [review]

**Pull request merged**
