### PR TITLE
Email validation/verification and Password change

### PR DESCRIPTION
**Pull request by ChillinRage**
**see #34 for more details**

### Other features
- Password change: users will receive an OTP via email to update their passwords if they forgot.

can test around and see if it works, then approve/merge once can.

### CODE REVIEW

**Comment by inezkok** [comment]
sorry i think i accidentally clicked the wrong button yesterday while clearing local branches on my end...

**Comment by ChillinRage** [comment]
don't merge yet, I haven't test the changes post-conflict

**Comment by ChillinRage** [comment]
I think should be ok alr. Tested it a bit and it works. Can merge if y'all want.

**Review by inezkok — APPROVED** [review]
lgtm!

**Pull request merged**
